USE TuristickaAgencija;
GO

CREATE APPLICATION ROLE DataProviderAGENCIJA
WITH PASSWORD = 'Agencija#Lozinka123',
     DEFAULT_SCHEMA = api_agencija;
GO

GRANT SELECT, EXECUTE ON SCHEMA::api_agencija TO DataProviderAGENCIJA;
GO

DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::impl TO DataProviderAGENCIJA;
DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::spec TO DataProviderAGENCIJA;
DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::api_web TO DataProviderAGENCIJA;
GO

GRANT VIEW DEFINITION ON SYMMETRIC KEY::KljucEmail TO DataProviderAGENCIJA;
GRANT CONTROL ON CERTIFICATE::CertEmail TO DataProviderAGENCIJA;
GO

CREATE APPLICATION ROLE DataProviderWEB
WITH PASSWORD = 'Web#Lozinka123',
     DEFAULT_SCHEMA = api_web;
GO

GRANT SELECT, EXECUTE ON SCHEMA::api_web TO DataProviderWEB;
GO

DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::impl TO DataProviderWEB;
DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::spec TO DataProviderWEB;
DENY SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::api_agencija TO DataProviderWEB;
GO

PRINT N'Aplikacione uloge DataProviderAGENCIJA i DataProviderWEB su kreirane.';
GO
